config/routes.rb
Rails.application.routes.draw do
  get 'sales_reports/index'
  post "generate_sales_reports", to: "sales_reports#generate"
  root "products#new"
  resources :reserve_or_purchases, except: [:show]  
  resources :customers, except: [:show]  
  resources :change_histories, except: [:show]  
  resources :suppliers, except: [:show]  
  resources :products, except: [:show]  


  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/change_history.rb
class ChangeHistory < ApplicationRecord
  belongs_to :product
end

app/controllers/change_histories_controller.rb
class ChangeHistoriesController < ApplicationController
  before_action :set_change_history, only: %i[ show edit update destroy ]

  # GET /change_histories or /change_histories.json
  def index
    @change_histories = ChangeHistory.all
  end

  # GET /change_histories/1 or /change_histories/1.json
  def show
  end

  # GET /change_histories/new
  def new
    @change_history = ChangeHistory.new
  end

  # GET /change_histories/1/edit
  def edit
  end

  # POST /change_histories or /change_histories.json
  def create
    @change_history = ChangeHistory.new(change_history_params)

    respond_to do |format|
      if @change_history.save
        format.html { redirect_to @change_history, notice: "Change history was successfully created." }
        format.json { render :show, status: :created, location: @change_history }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @change_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /change_histories/1 or /change_histories/1.json
  def update
    respond_to do |format|
      if @change_history.update(change_history_params)
        format.html { redirect_to @change_history, notice: "Change history was successfully updated." }
        format.json { render :show, status: :ok, location: @change_history }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @change_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /change_histories/1 or /change_histories/1.json
  def destroy
    @change_history.destroy!

    respond_to do |format|
      format.html { redirect_to change_histories_path, status: :see_other, notice: "Change history was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_change_history
      @change_history = ChangeHistory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def change_history_params
      params.require(:change_history).permit(:modification_date, :change_description, :product_id)
    end
end

app/helpers/change_histories_helper.rb
module ChangeHistoriesHelper
end

app/views/change_histories/_change_history.html.erb
<div id="<%= dom_id change_history %>">
  <p>
    <strong>Modification date:</strong>
    <%= change_history.modification_date %>
  </p>

  <p>
    <strong>Change description:</strong>
    <%= change_history.change_description %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= change_history.product_id %>
  </p>

</div>

app/views/change_histories/_form.html.erb
<%= form_with(model: change_history) do |form| %>
  <% if change_history.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(change_history.errors.count, "error") %> prohibited this change_history from being saved:</h2>

      <ul>
        <% change_history.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :modification_date, style: "display: block" %>
    <%= form.date_field :modification_date %>
  </div>

  <div>
    <%= form.label :change_description, style: "display: block" %>
    <%= form.text_field :change_description %>
  </div>

  <div>
    <%= form.label :product_id, style: "display: block" %>
    <%= form.text_field :product_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/change_histories/edit.html.erb
<h1>Editing change history</h1>

<%= render "form", change_history: @change_history %>

<br>

<div>
  <%= link_to "Show this change history", @change_history %> |
  <%= link_to "Back to change histories", change_histories_path %>
</div>

app/views/change_histories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Change histories</h1>

<div id="change_histories">
  <% @change_histories.each do |change_history| %>
    <%= render change_history %>
    <p>
      <%= link_to "Show this change history", change_history %>
    </p>
  <% end %>
</div>

<%= link_to "New change history", new_change_history_path %>

app/views/change_histories/new.html.erb
<h1>New change history</h1>

<%= render "form", change_history: @change_history %>

<br>

<div>
  <%= link_to "Back to change histories", change_histories_path %>
</div>

app/views/change_histories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @change_history %>

<div>
  <%= link_to "Edit this change history", edit_change_history_path(@change_history) %> |
  <%= link_to "Back to change histories", change_histories_path %>

  <%= button_to "Destroy this change history", @change_history, method: :delete %>
</div>