config/routes.rb
Rails.application.routes.draw do
  get 'sales_reports/index'
  post "generate_sales_reports", to: "sales_reports#generate"
  root "products#new"
  resources :reserve_or_purchases, except: [:show]  
  resources :customers, except: [:show]  
  resources :change_histories, except: [:show]  
  resources :suppliers, except: [:show]  
  resources :products, except: [:show]  


  namespace :authentication, path: '', as: '' do
    resources :users, only: [:index,:new, :create]
    resources :sessions, only: [:new, :create, :destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[ show edit update destroy ]

  # GET /suppliers or /suppliers.json
  def index
    @suppliers = Supplier.all
  end

  # GET /suppliers/1 or /suppliers/1.json
  def show
  end

  # GET /suppliers/new
  def new
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
  end

  # POST /suppliers or /suppliers.json
  def create
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to @supplier, notice: "Supplier was successfully created." }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1 or /suppliers/1.json
  def update
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to @supplier, notice: "Supplier was successfully updated." }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1 or /suppliers/1.json
  def destroy
    @supplier.destroy!

    respond_to do |format|
      format.html { redirect_to suppliers_path, status: :see_other, notice: "Supplier was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplier_params
      params.require(:supplier).permit(:supplier_name, :supplier_phone, :supplier_address)
    end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <% if supplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supplier.errors.count, "error") %> prohibited this supplier from being saved:</h2>

      <ul>
        <% supplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :supplier_name, style: "display: block" %>
    <%= form.text_field :supplier_name %>
  </div>

  <div>
    <%= form.label :supplier_phone, style: "display: block" %>
    <%= form.text_field :supplier_phone %>
  </div>

  <div>
    <%= form.label :supplier_address, style: "display: block" %>
    <%= form.text_field :supplier_address %>
  </div>

  <div>
    <%= form.submit "Submit", class: "complete-sale-button" %>
  </div>
<% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <td>
    <%= supplier.supplier_name %>
  </td>

  <td>
    <%= supplier.supplier_phone %>
  </td>

  <td>
    <%= supplier.supplier_address %>
  </td>
</div>

app/views/suppliers/edit.html.erb
<h1>Editing supplier</h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to "Show this supplier", @supplier %> |
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/index.html.erb
<style>

  .content {
    flex: 1;
    padding: 2rem;
  }

  .content-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 2rem;
  }

  .content-header h2 {
      font-size: 1.5rem;
      color: #2c3e50;
  }

  .add-btn {
      background-color: #3498db;
      color: white;
      border: none;
      padding: 0.75rem 1.5rem;
      border-radius: 4px;
      cursor: pointer;
  }

  /* Tabla */
  table {
      width: 100%;
      background-color: white;
      border-radius: 8px;
      border-collapse: collapse;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
  }

  th, td {
      padding: 1rem;
      text-align: left;
      border-bottom: 1px solid #ddd;
  }

  th {
      background-color: #f8f9fa;
      font-weight: 600;
      color: #333;
  }

  /* Botones de acción */
  .edit-btn, .delete-btn {
      padding: 0.5rem 1rem;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      margin-right: 0.5rem;
  }

  .edit-btn {
      background-color: #3498db;
      color: white;
  }

  .delete-btn {
      background-color: #e74c3c;
      color: white;
  }

  /* Responsive */
  @media (max-width: 768px) {
      .main-container {
          flex-direction: column;
      }
      
      .sidebar {
          width: 100%;
      }
      
      .content {
          padding: 1rem;
      }
  }
</style>

<p style="color: green"><%= notice %></p>

<div class="content-header">
  <h1>Suppliers</h1>
 <%= link_to new_supplier_path do %>
    <button class="add-btn">Agregar Proveedor</button>
  <% end %>

</div>



<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Dirección</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  
    <% @suppliers.each do |supplier| %>
     <tr> <%= render supplier %>

      
      <td>
        <%= link_to edit_product_path(supplier), class: "edit-btn", style:"text-decoration: none" do %>
            Editar 
          <% end %>
        <%= button_to "Eliminar", supplier, method: :delete, class:"delete-btn"%>
      </td>
    <% end %>
  </tr>
</table>

app/views/suppliers/new.html.erb
<style>
  .content {
    width: 80%;
    padding: 20px;
  }
  
  h2 {
    margin-bottom: 20px;
  }
  
  .new-sale-form {
    background-color: #ffffff;
    padding: 20px;
    border-radius: 8px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
  }
  
  .form-group {
    margin-bottom: 15px;
  }
  
  label {
    display: block;
    font-weight: bold;
    margin-bottom: 5px;
  }
  
  input, select {
    width: 100%;
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 5px;
  }
  
  input[disabled] {
    background-color: #e9ecef;
  }
  
  .form-actions {
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
  }
  
  .complete-sale-button {
    background-color: #28a745;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 5px;
    cursor: pointer;
  }
  
  .cancel-button {
    background-color: #dc3545;
    color: white;
    border: none;
    padding: 10px 15px;
    border-radius: 5px;
    cursor: pointer;
  }
  

</style>

<main class="content">
<div class="new-sale-form">
<h1>New supplier</h1>

<%= render "form", supplier: @supplier %>
</div>
</main">

<br>

<div>
  <%= link_to "Back to suppliers", suppliers_path %>
</div>

app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>

<div>
  <%= link_to "Edit this supplier", edit_supplier_path(@supplier) %> |
  <%= link_to "Back to suppliers", suppliers_path %>

  <%= button_to "Destroy this supplier", @supplier, method: :delete %>
</div>